# BASTION (Caldera-Wazuh Integration Plugin) Default Configuration

bastion:
  # Wazuh Manager API Configuration
  # For security, using environment variable (WAZUH_PASSWORD) is recommended.
  wazuh_manager_url: "https://localhost:55000"
  wazuh_username: "wazuh"
  wazuh_password: "" # Set 'WAZUH_PASSWORD' env var or fill this only in dev local

  # Wazuh Indexer (OpenSearch) Configuration
  # For security, using environment variable (WAZUH_INDEXER_PASSWORD) is recommended.
  wazuh_indexer_url: "https://localhost:9200"

  # SSL Verification (false for development, true for production)
  verify_ssl: false

  # Alert monitoring interval (seconds)
  alert_query_interval: 300

  # Enable continuous monitoring
  enable_continuous_monitoring: false

  # Detection analysis configuration
  detection:
    min_alert_level: 7  # Minimum alert severity level (0-15)
    correlation_window: 300  # Correlation analysis time window (seconds)

  # Adaptive operation configuration
  adaptive:
    enabled: false
    auto_adjust_ttps: false  # Enable automatic TTP adjustment
